# Copyright (c) 1997-2016 The CSE Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file.
docs-branch: "gh-pages"
src-dir: "src"
reference-dir: "config/reference"
cssnano-exe: "node_modules/.bin/cssnano"
html-minifier-exe: "node_modules/.bin/html-minifier"
use-node?: true
use-ghpages?: true
build-pdf?: true
build-dir: 'build'
output-dir: 'build/output'
remote-repo-url: "https://github.com/cse-sim/cse.git"
draft?: true
