# Copyright (c) 1997-2016 The CSE Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file.
docs-branch: "gh-pages"
src-dir: "src"
media-dir: "src/media"
css-dir: "config/css"
template-dir: "config/template"
reference-dir: "config/reference"
cssnano-exe: "node_modules/.bin/cssnano"
html-minifier-exe: "node_modules/.bin/html-minifier"
use-node?: false
use-ghpages?: true
build-dir: 'build'
md-temp-dir: 'build/temp/md'
html-temp-dir: 'build/temp/html'
pdf-temp-dir: 'build/temp/pdf'
probes-temp-dir: 'build/temp/probes'
html-output-dir: 'build/output'
pdf-output-dir: 'build/output/pdfs'
log-dir: 'build/logs'
pdf-header: "\"CSE User's Manual\""
pdf-footer: "Time.now.strftime(\"%FT%T%:z\")"
generate-probes-documentation?: true
pdf-skip-list:
  - index.md
options:
  pandoc:
    "*":
      - "--parse-raw"
      - "--standalone"
      - "--wrap=none"
    "pdf":
      - '--variable geometry="margin=1in"'
      - '--variable urlcolor=cyan'
      - "--latex-engine=xelatex"
      - "--table-of-contents"
      - "--toc-depth=3"
      - "--number-sections"
      - "--smart"
      - "--template=template.tex"
      - "--listings"
      - "--from markdown"
    "md":
      - "--atx-headers"
      - "--normalize"
      - "--to markdown"
      - "--from markdown"
    "html":
      - "--to html5"
      - "--from markdown"
      - "--mathjax"
      - "--css=css/base.css"
      - "--table-of-contents"
      - "--toc-depth=3"
      - "--number-sections"
      - "--smart"

