docs-branch: "gh-pages"
src-dir: "src"
media-dir: "src/media"
css-dir: "config/css"
template-dir: "config/template"
reference-dir: "config/reference"
cssnano-exe: "node_modules/.bin/cssnano"
html-minifier-exe: "node_modules/.bin/html-minifier"
use-node?: false
build-dir: 'build'
md-temp-dir: 'build/temp/md'
html-temp-dir: 'build/temp/html'
pdf-temp-dir: 'build/temp/pdf'
html-output-dir: 'build/output/html'
pdf-output-dir: 'build/output/html/pdfs'
log-dir: 'build/logs'
pdf-header: "\"CSE User's Manual\""
pdf-footer: "Time.now.strftime(\"%FT%T%:z\")"
pdf-skip-list:
  - index.md
options:
  pandoc:
    "*":
      - "--parse-raw"
      - "--standalone"
      - "--wrap=none"
    "pdf":
      - '--variable geometry="margin=1in"'
      - '--variable urlcolor=cyan'
      - "--latex-engine=xelatex"
      - "--table-of-contents"
      - "--toc-depth=3"
      - "--number-sections"
      - "--smart"
      - "--template=template.tex"
      - "--listings"
    "md":
      - "--atx-headers"
      - "--normalize"
      - "--to markdown"
    "html":
      - "--to html5"
      - "--mathjax"
      - "--css=css/base.css"
      - "--table-of-contents"
      - "--toc-depth=3"
      - "--number-sections"
      - "--smart"

